- name: install gnupg
  apt:
    name: gnupg
    state: present
    update_cache: yes

- name: import the public key used by the package manamegement system
  shell: wget -qO - https://www.mongodb.org/static/pgp/server-{{ mongo_version }}.asc | apt-key add -

- name: create the mongodb-org-{{ mongo_version }}.list in Debain {{ ansible_distribution_release }}
  copy:
    dest: /etc/apt/sources.list.d/mongodb-org-{{ mongo_version }}.list
    content: deb http://repo.mongodb.org/apt/debian {{ ansible_distribution_release }}/mongodb-org/{{ mongo_version }} main
    mode: '0644'

- name: install the MongoDB packages
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
